FROM node:21.5.0-bookworm

#WORKDIR /broyden/test

#EXPOSE 9229

RUN npm i -g typescript
# && npm install --save-dev jest \
# && npm install --save-dev @babel/preset-typescript \
# && npm install --save-dev ts-jest \
# && npm install --save-dev @jest/globals
EXPOSE 3000
# CMD ["node", "--inspect-brk=0.0.0.0:9229", "--require", "ts-node/register", "./node_modules/.bin/jest", "--runInBand"]
